// Auto-generated by immersphere-production-orchestrator v0.4.0
import type { ClientDemo } from "@/types/clientDemo";

export const sandhouseInmobiliaria: ClientDemo = {
  client: {
    slug: "sandhouse-inmobiliaria",
    name: "Sandhouse Inmobiliaria",
    sector: "Inmobiliaria",
    zone: "Torrevieja",
    website: "https://www.sandhouse.es/contactos",
    logo: "",
    primaryColor: "#1a1a2e",
    accentColor: "#d4af37",
  },
  audit: {
    digitalPresenceScore: 56,
    mobileFriendly: false,
    hasVideoContent: false,
    hasVirtualTour: false,
    conversionRateEstimate: "0.8%",
    opportunityDetected: "Experiencia inmobiliaria premium",
  },
  hero: {
    headline: "Sandhouse Inmobiliaria — Experiencia Inmobiliaria Premium",
    subheadline: "Experiencia inmobiliaria premium",
    heroImage: "",
    heroVideo: "",
    propertyImages: [],
  },
  comparison: {
    currentWebsite: "https://www.sandhouse.es/contactos",
    currentScreenshot: "",
    immerspherePreview: "https://aurum-properties-boutique.vercel.app/sandhouse-inmobiliaria",
    improvements: [
      "Experiencia visual inmersiva con motion design",
      "Galería de propiedades optimizada para conversión",
      "Integración directa con WhatsApp para leads calientes",
      "Presencia mobile-first premium",
    ],
  },
  visualExperience: {
    embedUrl: "https://rubik-sota-director-de-orquesta.vercel.app/gesture-lab/sandhouse-inmobiliaria-v1",
    standaloneUrl: "https://aurum-properties-boutique.vercel.app/visual-experience/sandhouse-inmobiliaria",
    bannerPackUrl: "https://rubik-sota-director-de-orquesta.vercel.app/dynamic-motion-banner/sandhouse-inmobiliaria/banner-pack",
    bannerVerticalUrl: "https://rubik-sota-director-de-orquesta.vercel.app/dynamic-motion-banner/sandhouse-inmobiliaria/banner-vertical",
    bannerHorizontalUrl: "https://rubik-sota-director-de-orquesta.vercel.app/dynamic-motion-banner/sandhouse-inmobiliaria/banner-horizontal",
  },
  highIntentContact: {
    label: "Solicitar propuesta premium",
    primaryHref: "#contact",
    secondaryHref: "#contact",
    emailHref: "#contact",
  },
  salesContact: {
    emailSubject: "Propuesta Premium Immersphere — Sandhouse Inmobiliaria",
    emailBody: "Hola,\n\nAdjunto propuesta de experiencia inmobiliaria premium para Sandhouse Inmobiliaria.\n\nDemo interactivo: https://aurum-properties-boutique.vercel.app/sandhouse-inmobiliaria\n\n¿Cuándo podemos agendar una llamada de 20 minutos?\n\nSaludos,\nEquipo Immersphere",
    whatsappMessage: "Hola Sandhouse Inmobiliaria, te comparto el demo premium de tu nueva presencia digital: https://aurum-properties-boutique.vercel.app/sandhouse-inmobiliaria",
  },
  immersphereServices: {
    landing: "https://aurum-properties-boutique.vercel.app/sandhouse-inmobiliaria",
    webCompleta: "https://aurum-properties-boutique.vercel.app/sandhouse-inmobiliaria-web-completa",
    visualExperience: "https://aurum-properties-boutique.vercel.app/visual-experience/sandhouse-inmobiliaria",
    bannerPack: "https://rubik-sota-director-de-orquesta.vercel.app/dynamic-motion-banner/sandhouse-inmobiliaria/banner-pack",
  },
};
