// Auto-generated by immersphere-production-orchestrator v0.4.0
import type { ClientDemo } from "@/types/clientDemo";

export const torreviejaSur: ClientDemo = {
  client: {
    slug: "torrevieja-sur",
    name: "Torrevieja Sur",
    sector: "Inmobiliaria",
    zone: "Torrevieja",
    website: "https://torreviejasur.com/",
    logo: "",
    primaryColor: "#1a1a2e",
    accentColor: "#d4af37",
  },
  audit: {
    digitalPresenceScore: 68,
    mobileFriendly: false,
    hasVideoContent: false,
    hasVirtualTour: false,
    conversionRateEstimate: "0.8%",
    opportunityDetected: "Experiencia inmobiliaria premium",
  },
  hero: {
    headline: "Torrevieja Sur — Experiencia Inmobiliaria Premium",
    subheadline: "Experiencia inmobiliaria premium",
    heroImage: "",
    heroVideo: "",
    propertyImages: [],
  },
  comparison: {
    currentWebsite: "https://torreviejasur.com/",
    currentScreenshot: "",
    immerspherePreview: "https://aurum-properties-boutique.vercel.app/torrevieja-sur",
    improvements: [
      "Experiencia visual inmersiva con motion design",
      "Galería de propiedades optimizada para conversión",
      "Integración directa con WhatsApp para leads calientes",
      "Presencia mobile-first premium",
    ],
  },
  visualExperience: {
    embedUrl: "https://rubik-sota-director-de-orquesta.vercel.app/gesture-lab/torrevieja-sur-v1",
    standaloneUrl: "https://aurum-properties-boutique.vercel.app/visual-experience/torrevieja-sur",
    bannerPackUrl: "https://rubik-sota-director-de-orquesta.vercel.app/dynamic-motion-banner/torrevieja-sur/banner-pack",
    bannerVerticalUrl: "https://rubik-sota-director-de-orquesta.vercel.app/dynamic-motion-banner/torrevieja-sur/banner-vertical",
    bannerHorizontalUrl: "https://rubik-sota-director-de-orquesta.vercel.app/dynamic-motion-banner/torrevieja-sur/banner-horizontal",
  },
  highIntentContact: {
    label: "Solicitar propuesta premium",
    primaryHref: "#contact",
    secondaryHref: "#contact",
    emailHref: "#contact",
  },
  salesContact: {
    emailSubject: "Propuesta Premium Immersphere — Torrevieja Sur",
    emailBody: "Hola,\n\nAdjunto propuesta de experiencia inmobiliaria premium para Torrevieja Sur.\n\nDemo interactivo: https://aurum-properties-boutique.vercel.app/torrevieja-sur\n\n¿Cuándo podemos agendar una llamada de 20 minutos?\n\nSaludos,\nEquipo Immersphere",
    whatsappMessage: "Hola Torrevieja Sur, te comparto el demo premium de tu nueva presencia digital: https://aurum-properties-boutique.vercel.app/torrevieja-sur",
  },
  immersphereServices: {
    landing: "https://aurum-properties-boutique.vercel.app/torrevieja-sur",
    webCompleta: "https://aurum-properties-boutique.vercel.app/torrevieja-sur-web-completa",
    visualExperience: "https://aurum-properties-boutique.vercel.app/visual-experience/torrevieja-sur",
    bannerPack: "https://aurum-properties-boutique.vercel.app/banners/torrevieja-sur",
  },
};
