// Auto-generated by immersphere-production-orchestrator v0.4.0
import type { ClientDemo } from "@/types/clientDemo";

export const unitedRealEstate: ClientDemo = {
  client: {
    slug: "united-real-estate",
    name: "United Real Estate",
    sector: "Inmobiliaria",
    zone: "Dehesa de Campoamor",
    website: "https://unitedrealestate.es/contacto/",
    logo: "https://unitedrealestate.es/wp-content/uploads/united-logo-bl.png",
    primaryColor: "#1a1a2e",
    accentColor: "#d4af37",
  },
  audit: {
    digitalPresenceScore: 68,
    mobileFriendly: false,
    hasVideoContent: false,
    hasVirtualTour: false,
    conversionRateEstimate: "0.8%",
    opportunityDetected: "Experiencia inmobiliaria premium",
  },
  hero: {
    headline: "United Real Estate — Experiencia Inmobiliaria Premium",
    subheadline: "Experiencia inmobiliaria premium",
    heroImage: "https://fotos15.apinmo.com/6689/23276849/4-1.jpg",
    heroVideo: "",
    propertyImages: ["https://fotos15.apinmo.com/6689/23276849/4-6.jpg","https://fotos15.apinmo.com/6689/23276849/4-7.jpg","https://fotos15.apinmo.com/6689/23276849/4-8.jpg","https://fotos15.apinmo.com/6689/23276849/4-9.jpg"],
  },
  comparison: {
    currentWebsite: "https://unitedrealestate.es/contacto/",
    currentScreenshot: "",
    immerspherePreview: "https://aurum-properties-boutique.vercel.app/united-real-estate",
    improvements: [
      "Experiencia visual inmersiva con motion design",
      "Galería de propiedades optimizada para conversión",
      "Integración directa con WhatsApp para leads calientes",
      "Presencia mobile-first premium",
    ],
  },
  visualExperience: {
    embedUrl: "https://rubik-sota-director-de-orquesta.vercel.app/gesture-lab/united-real-estate-v1",
    standaloneUrl: "https://aurum-properties-boutique.vercel.app/visual-experience/united-real-estate",
    bannerPackUrl: "https://rubik-sota-director-de-orquesta.vercel.app/dynamic-motion-banner/united-real-estate/banner-pack",
    bannerVerticalUrl: "https://rubik-sota-director-de-orquesta.vercel.app/dynamic-motion-banner/united-real-estate/banner-vertical",
    bannerHorizontalUrl: "https://rubik-sota-director-de-orquesta.vercel.app/dynamic-motion-banner/united-real-estate/banner-horizontal",
  },
  highIntentContact: {
    label: "Solicitar propuesta premium",
    primaryHref: "#contact",
    secondaryHref: "#contact",
    emailHref: "#contact",
  },
  salesContact: {
    emailSubject: "Propuesta Premium Immersphere — United Real Estate",
    emailBody: "Hola,\n\nAdjunto propuesta de experiencia inmobiliaria premium para United Real Estate.\n\nDemo interactivo: https://aurum-properties-boutique.vercel.app/united-real-estate\n\n¿Cuándo podemos agendar una llamada de 20 minutos?\n\nSaludos,\nEquipo Immersphere",
    whatsappMessage: "Hola United Real Estate, te comparto el demo premium de tu nueva presencia digital: https://aurum-properties-boutique.vercel.app/united-real-estate",
  },
  immersphereServices: {
    landing: "https://aurum-properties-boutique.vercel.app/united-real-estate",
    webCompleta: "https://aurum-properties-boutique.vercel.app/united-real-estate-web-completa",
    visualExperience: "https://aurum-properties-boutique.vercel.app/visual-experience/united-real-estate",
    bannerPack: "https://aurum-properties-boutique.vercel.app/banners/united-real-estate",
  },
};
