// Auto-generated by immersphere-production-orchestrator v0.4.0
import React from "react";

export function SandhouseBannerHorizontal() {
  return (
    <div style={{ display: "flex", justifyContent: "center", padding: "40px 24px" }}>
      <iframe
        src="https://rubik-sota-director-de-orquesta.vercel.app/dynamic-motion-banner/sandhouse-inmobiliaria/banner-horizontal"
        style={{ width: "728px", height: "90px", border: "none" }}
        title="banner-horizontal sandhouse-inmobiliaria"
        allow="autoplay"
      />
    </div>
  );
}
