// Auto-generated by immersphere-production-orchestrator v0.4.0
import React from "react";

export function SandhouseInmobiliariaVisualExperienceVisualExperience() {
  return (
    <div style={{ width: "100%", height: "100vh", overflow: "hidden" }}>
      <iframe
        src="https://rubik-sota-director-de-orquesta.vercel.app/gesture-lab/sandhouse-inmobiliaria-v1"
        style={{ width: "100%", height: "100vh", border: "none" }}
        title="visual-experience sandhouse-inmobiliaria"
        allow="autoplay"
      />
    </div>
  );
}
