// Auto-generated by immersphere-production-orchestrator v0.4.0
import React from "react";
import { sandhouseInmobiliaria } from "@/data/clientDemos/sandhouseInmobiliaria";

export function SandhouseLanding() {
  const cfg = sandhouseInmobiliaria;
  const ac = cfg.client.accentColor || "#d4af37";
  return (
    <main data-client-slug="sandhouse-inmobiliaria" style={{ background: "#0a0a0a", color: "#fff", fontFamily: "Arial,sans-serif", minHeight: "100vh" }}>
      <section style={{ position: "relative", height: "100vh", overflow: "hidden", display: "flex", alignItems: "center", justifyContent: "center" }}>
        
        <div style={{ position: "relative", zIndex: 1, textAlign: "center", padding: "0 24px", maxWidth: 800 }}>
          
          <h1 style={{ fontSize: "clamp(42px,8vw,96px)", fontWeight: 800, lineHeight: 1, marginBottom: 20 }}>Sandhouse Inmobiliaria</h1>
          <p style={{ fontSize: "clamp(18px,3vw,26px)", color: "rgba(255,255,255,0.8)", maxWidth: 680, margin: "0 auto 32px" }}>Experiencia inmobiliaria premium</p>
          <a href="#contact" target="_blank" rel="noopener" style={{ background: ac, color: "#000", fontWeight: 700, padding: "16px 32px", textDecoration: "none", fontSize: 16, display: "inline-block", borderRadius: 2 }}>Solicitar Propuesta Premium</a>
        </div>
      </section>

      <section style={{ padding: "80px 24px", background: "#111" }}>
        <h2 style={{ textAlign: "center", fontSize: 32, marginBottom: 40 }}>Experiencia Visual</h2>
        <div style={{ maxWidth: 1100, margin: "0 auto", borderRadius: 8, overflow: "hidden" }}>
          <iframe src={cfg.visualExperience.embedUrl} style={{ width: "100%", height: 600, border: "none" }} title="Visual Experience Sandhouse Inmobiliaria" />
        </div>
      </section>

      <section style={{ padding: "80px 24px", textAlign: "center" }}>
        <h2 style={{ fontSize: 32, marginBottom: 20 }}>¿Listo para transformar tu presencia?</h2>
        <p style={{ color: "rgba(255,255,255,0.7)", fontSize: 18, marginBottom: 40, maxWidth: 600, margin: "0 auto 40px" }}>Solicita una propuesta personalizada y descubre cómo Immersphere puede multiplicar tus leads.</p>
        <a href={cfg.highIntentContact.primaryHref} target="_blank" rel="noopener" style={{ background: ac, color: "#000", fontWeight: 700, padding: "20px 48px", textDecoration: "none", fontSize: 18, display: "inline-block", borderRadius: 2 }}>Solicitar Propuesta Premium</a>
      </section>
    </main>
  );
}
