// Auto-generated by immersphere-production-orchestrator v0.4.0
export function TorreviejaSurBannerVertical() {
  return (
    <div style={{ display: "flex", justifyContent: "center", padding: "40px 24px" }}>
      <iframe
        src="https://rubik-sota-director-de-orquesta.vercel.app/dynamic-motion-banner/torrevieja-sur/banner-vertical"
        style={{ width: "400px", height: "700px", border: "none" }}
        title="banner-vertical torrevieja-sur"
        allow="autoplay"
      />
    </div>
  );
}
