// Auto-generated by immersphere-production-orchestrator v0.4.0
import React from "react";

export function TorreviejaSurBannerPack() {
  return (
    <div style={{ display: "flex", justifyContent: "center", padding: "40px 24px" }}>
      <iframe
        src="https://rubik-sota-director-de-orquesta.vercel.app/dynamic-motion-banner/torrevieja-sur/banner-pack"
        style={{ width: "100%", height: "900px", border: "none" }}
        title="banner-pack torrevieja-sur"
        allow="autoplay"
      />
    </div>
  );
}
