// Auto-generated by immersphere-production-orchestrator v0.4.0
import React, { useEffect, useRef } from "react";
import { torreviejaSur } from "@/data/clientDemos/torreviejaSur";

export function TorreviejaSurWebCompleta() {
  const cfg = torreviejaSur;
  const videoRef = useRef<HTMLVideoElement>(null);
  useEffect(() => { videoRef.current?.play().catch(() => {}); }, []);
  const ac = cfg.client.accentColor || "#d4af37";

  return (
    <main data-client-slug="torrevieja-sur" style={{ background: "#0a0a0a", color: "#fff", fontFamily: "Arial,sans-serif" }}>
      <section style={{ position: "relative", height: "100vh", overflow: "hidden", display: "flex", alignItems: "center", justifyContent: "center" }}>
        {cfg.hero.heroVideo ? (
          <video ref={videoRef} src={cfg.hero.heroVideo} muted loop playsInline style={{ position: "absolute", inset: 0, width: "100%", height: "100%", objectFit: "cover", opacity: 0.5 }} />
        ) : cfg.hero.heroImage ? (
          <img src={cfg.hero.heroImage} alt="" style={{ position: "absolute", inset: 0, width: "100%", height: "100%", objectFit: "cover", opacity: 0.45 }} />
        ) : null}
        <div style={{ position: "relative", textAlign: "center", padding: "0 24px" }}>
          {cfg.client.logo && <img src={cfg.client.logo} alt={cfg.client.name} style={{ maxHeight: 64, marginBottom: 24, filter: "brightness(0) invert(1)" }} />}
          <h1 style={{ fontSize: "clamp(42px,8vw,96px)", fontWeight: 800, lineHeight: 1, marginBottom: 20 }}>{cfg.client.name}</h1>
          <p style={{ fontSize: "clamp(18px,3vw,26px)", color: "rgba(255,255,255,0.8)", maxWidth: 680, margin: "0 auto 32px" }}>{cfg.hero.subheadline}</p>
          <a href={cfg.highIntentContact.primaryHref} target="_blank" rel="noopener" style={{ background: ac, color: "#000", fontWeight: 700, padding: "16px 32px", textDecoration: "none", fontSize: 16, display: "inline-block" }}>Solicitar Propuesta Premium</a>
        </div>
      </section>

      <section style={{ padding: "80px 24px", background: "#111" }}>
        <h2 style={{ textAlign: "center", fontSize: 32, marginBottom: 40 }}>Experiencia Visual</h2>
        <div style={{ maxWidth: 1100, margin: "0 auto", borderRadius: 8, overflow: "hidden" }}>
          <iframe src="https://rubik-sota-director-de-orquesta.vercel.app/gesture-lab/torrevieja-sur-v1" style={{ width: "100%", height: 600, border: "none" }} title="Visual Experience Torrevieja Sur" />
        </div>
      </section>

      <section style={{ padding: "80px 24px" }}>
        <h2 style={{ textAlign: "center", fontSize: 32, marginBottom: 40 }}>Galería de Propiedades</h2>
        <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fill,minmax(320px,1fr))", gap: 16, maxWidth: 1100, margin: "0 auto" }}>
          {cfg.hero.propertyImages.slice(0, 6).map((src, i) => (
            <img key={i} src={src} alt="" style={{ width: "100%", aspectRatio: "4/3", objectFit: "cover", borderRadius: 4 }} />
          ))}
        </div>
      </section>

      <section style={{ padding: "80px 24px", background: "#111" }}>
        <h2 style={{ textAlign: "center", fontSize: 32, marginBottom: 40 }}>Tu Presencia Digital Transformada</h2>
        <div style={{ maxWidth: 900, margin: "0 auto" }}>
          {cfg.comparison.improvements.map((item, i) => (
            <div key={i} style={{ display: "flex", gap: 16, marginBottom: 20, alignItems: "flex-start" }}>
              <span style={{ color: ac, fontSize: 20, flexShrink: 0 }}>✓</span>
              <p style={{ color: "rgba(255,255,255,0.85)", fontSize: 16 }}>{item}</p>
            </div>
          ))}
        </div>
      </section>

      <section style={{ padding: "80px 24px" }}>
        <h2 style={{ textAlign: "center", fontSize: 32, marginBottom: 40 }}>Banners de Campaña</h2>
        <div style={{ display: "flex", flexWrap: "wrap", gap: 32, justifyContent: "center", maxWidth: 1200, margin: "0 auto" }}>
          <iframe src={cfg.visualExperience.bannerVerticalUrl} style={{ width: 400, height: 700, border: "none", borderRadius: 4 }} title="Banner Vertical" />
          <iframe src={cfg.visualExperience.bannerHorizontalUrl} style={{ width: 728, height: 90, border: "none", borderRadius: 4 }} title="Banner Horizontal" />
        </div>
      </section>

      <section style={{ padding: "80px 24px", background: "#111" }}>
        <h2 style={{ textAlign: "center", fontSize: 32, marginBottom: 40 }}>Servicios Immersphere</h2>
        <div style={{ maxWidth: 800, margin: "0 auto", display: "grid", gridTemplateColumns: "1fr 1fr", gap: 24 }}>
          {([["Landing Page Premium", cfg.immersphereServices.landing], ["Web Completa", cfg.immersphereServices.webCompleta], ["Visual Experience", cfg.immersphereServices.visualExperience], ["Banner Pack", cfg.immersphereServices.bannerPack]] as [string, string][]).map(([label, href]) => (
            <a key={label} href={href} target="_blank" rel="noopener" style={{ background: "#1a1a1a", border: "1px solid #333", padding: "20px 24px", textDecoration: "none", color: "#fff", borderRadius: 4, display: "block" }}>
              <span style={{ color: ac, fontSize: 12, letterSpacing: ".15em", textTransform: "uppercase" as const, display: "block", marginBottom: 8 }}>Abrir</span>
              <strong>{label}</strong>
            </a>
          ))}
        </div>
      </section>

      <section style={{ padding: "80px 24px" }}>
        <h2 style={{ textAlign: "center", fontSize: 32, marginBottom: 40 }}>Auditoría Digital</h2>
        <div style={{ maxWidth: 700, margin: "0 auto", background: "#111", borderRadius: 8, padding: "32px 40px" }}>
          {([["Puntuación actual", String(cfg.audit.digitalPresenceScore) + "/100"], ["Mobile friendly", cfg.audit.mobileFriendly ? "Sí" : "No"], ["Conversión estimada", cfg.audit.conversionRateEstimate]] as [string, string][]).map(([k, v]) => (
            <div key={k} style={{ display: "flex", justifyContent: "space-between", marginBottom: 12 }}>
              <span style={{ color: "#aaa" }}>{k}</span><strong style={{ color: k === "Puntuación actual" ? ac : "#fff" }}>{v}</strong>
            </div>
          ))}
        </div>
      </section>

      <section style={{ padding: "100px 24px", textAlign: "center", background: "linear-gradient(135deg,#0a0a0a 0%,#1a1a1a 100%)" }}>
        <h2 style={{ fontSize: 40, marginBottom: 20 }}>¿Listo para transformar tu presencia?</h2>
        <p style={{ color: "rgba(255,255,255,0.7)", fontSize: 18, marginBottom: 40, maxWidth: 600, margin: "0 auto 40px" }}>Solicita una propuesta personalizada y descubre cómo Immersphere puede multiplicar tus leads.</p>
        <a href={cfg.highIntentContact.primaryHref} target="_blank" rel="noopener" style={{ background: ac, color: "#000", fontWeight: 700, padding: "20px 48px", textDecoration: "none", fontSize: 18, display: "inline-block", borderRadius: 2 }}>Solicitar Propuesta Premium</a>
      </section>
    </main>
  );
}
