// Auto-generated by immersphere-production-orchestrator v0.4.0
export function TorreviejaSurBannerHorizontal() {
  return (
    <div style={{ display: "flex", justifyContent: "center", padding: "40px 24px" }}>
      <iframe
        src="https://rubik-sota-director-de-orquesta.vercel.app/dynamic-motion-banner/torrevieja-sur/banner-horizontal"
        style={{ width: "728px", height: "90px", border: "none" }}
        title="banner-horizontal torrevieja-sur"
        allow="autoplay"
      />
    </div>
  );
}
