// Auto-generated by immersphere-production-orchestrator v0.4.0
import React from "react";

export function UnitedRealEstateBannerVertical() {
  return (
    <div style={{ display: "flex", justifyContent: "center", padding: "40px 24px" }}>
      <iframe
        src="https://rubik-sota-director-de-orquesta.vercel.app/dynamic-motion-banner/united-real-estate/banner-vertical"
        style={{ width: "400px", height: "700px", border: "none" }}
        title="banner-vertical united-real-estate"
        allow="autoplay"
      />
    </div>
  );
}
